server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri:  lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - Between=2022-08-18T16:00:13.824+08:00[Asia/Shanghai]    #在指定时间之后才能访问
#            - Cookie=username,ljf    #在指定时间之后才能访问
            #ZonedDateTime now = ZonedDateTime.now();   获取当前时间

#        - id: payment_route2
#          uri: http://localhost:
#          uri:  lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
#          predicates:
#            Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/